ol:
  config:
    apiPackage: com.mf_rpc_sdk.openlegacy
    apiSourceFolder: src/main/java
    backendSolution: mf-rpc
    designtimeContext: default
    frontendSolution: java
    generateTest: true
    provider: openlegacy-rpc-mf
    sourceFetcher: sourceFetcher
    webPackage: com.mf_rpc_sdk.openlegacy.web
